class FilipinoPronunciationService {
  // Filipino vowel pronunciation variations
  static const Map<String, List<String>> filipinoVowelVariations = {
    'a': ['a', 'ah', 'ey'],
    'e': ['e', 'eh', 'ay'],
    'i': ['i', 'ee', 'eye', 'e'],
    'o': ['o', 'oh', 'ow', 'u'],
    'u': ['u', 'oo', 'you', 'o'],
  };

  // Common Filipino consonant variations
  static const Map<String, List<String>> filipinoConsonantVariations = {
    'r': ['r', 'rr', 'd'],
    'ny': ['ny', 'ñ', 'ni', 'n'],
    'ng': ['ng', 'n', 'nang'],
    's': ['s', 'z'],
    'c': ['c', 'k', 's'],
    'f': ['f', 'p'],
    'v': ['v', 'b'],
    't': ['t', 'd'],
    'k': ['k', 'c', 'q'],
  };

  // Common Filipino word variations
  static const Map<String, List<String>> filipinoWordVariations = {
    // Level 1 words
    'a': ['a', 'ah', 'ey'],
    'b': ['b', 'bi', 'be'],
    'c': ['c', 'si', 'se'],
    'd': ['d', 'di', 'de'],
    'e': ['e', 'eh', 'ay'],
    'f': ['f', 'ef', 'pit'],
    'g': ['g', 'ji', 'dyi'],
    'h': ['h', 'eych', 'ets'],
    'i': ['i', 'ay', 'eye'],
    'j': ['j', 'dyey', 'hwey'],
    'k': ['k', 'key', 'key'],
    'l': ['l', 'el', 'el'],
    'm': ['m', 'em', 'em'],
    'n': ['n', 'en', 'en'],
    'o': ['o', 'oh', 'ow'],
    'p': ['p', 'pi', 'pi'],
    'q': ['q', 'kyu', 'kyu'],
    'r': ['r', 'ar', 'ar'],
    's': ['s', 'es', 'es'],
    't': ['t', 'ti', 'ti'],
    'w': ['w', 'dobolyu', 'dobol'],
    'x': ['x', 'eks', 'eks'],
    'y': ['y', 'way', 'way'],
    'z': ['z', 'zi', 'zi'],

    // Level 2 words
    'ah': ['ah', 'a', 'ha'],
    'am': ['am', 'em', 'um'],
    'an': ['an', 'en', 'un'],
    'as': ['as', 'es', 'us'],
    'at': ['at', 'aet', 'ad'],
    'ay': ['ay', 'ey', 'a'],
    'ba': ['ba', 'bha', 'wa'],
    'be': ['be', 'bi', 'bey'],
    'bi': ['bi', 'bay', 'bei'],
    'bo': ['bo', 'bho', 'bu'],
    'bu': ['bu', 'bhu', 'boo'],
    'by': ['by', 'bay', 'bai'],
    'da': ['da', 'dha', 'ra'],
    'do': ['do', 'dho', 'du'],
    'du': ['du', 'dhu', 'doo'],
    'ed': ['ed', 'id', 'et'],
    'eh': ['eh', 'e', 'hay'],
    'ex': ['ex', 'eks', 'ecks'],
    'go': ['go', 'goh', 'gu'],
    'he': ['he', 'hi', 'hey'],
    'hi': ['hi', 'hay', 'hey'],
    'id': ['id', 'it', 'ed'],
    'if': ['if', 'ip', 'iv'],
    'im': ['im', 'em', 'um'],
    'in': ['in', 'en', 'un'],
    'is': ['is', 'es', 'iz'],
    'it': ['it', 'id', 'at'],
    'ja': ['ja', 'dya', 'ha'],
    'je': ['je', 'dye', 'hey'],
    'ji': ['ji', 'dyi', 'hi'],
    'jo': ['jo', 'dyo', 'ho'],
    'ju': ['ju', 'dyu', 'hu'],
    'ka': ['ka', 'kha', 'ga'],
    'ke': ['ke', 'ki', 'key'],
    'ki': ['ki', 'kay', 'kai'],
    'ko': ['ko', 'kho', 'ku'],
    'ku': ['ku', 'khu', 'koo'],
    'la': ['la', 'lha', 'ra'],
    'lo': ['lo', 'lho', 'lu'],
    'ma': ['ma', 'mha', 'wa'],
    'me': ['me', 'mi', 'mey'],
    'mi': ['mi', 'may', 'mai'],
    'mo': ['mo', 'mho', 'mu'],
    'mu': ['mu', 'mhu', 'moo'],
    'my': ['my', 'may', 'mai'],
    'na': ['na', 'nha', 'nya'],
    'ne': ['ne', 'ni', 'ney'],
    'ni': ['ni', 'nay', 'nyi'],
    'no': ['no', 'nho', 'nu'],
    'nu': ['nu', 'nhu', 'noo'],
    'of': ['of', 'ov', 'op'],
    'ok': ['ok', 'oke', 'okay'],
    'on': ['on', 'un', 'an'],
    'or': ['or', 'ur', 'ar'],
    'ox': ['ox', 'oks', 'oks'],
    'pa': ['pa', 'pha', 'fa'],
    'pe': ['pe', 'pi', 'pey'],
    'pi': ['pi', 'pay', 'pai'],
    'po': ['po', 'pho', 'pu'],
    'pu': ['pu', 'phu', 'poo'],
    'qi': ['qi', 'ki', 'chi'],
    'ra': ['ra', 'dha', 'la'],
    're': ['re', 'ri', 'rey'],
    'ri': ['ri', 'ray', 'rai'],
    'ro': ['ro', 'rho', 'ru'],
    'ru': ['ru', 'rhu', 'roo'],
    'so': ['so', 'sho', 'su'],
    'ta': ['ta', 'dha', 'da'],
    'te': ['te', 'ti', 'tey'],
    'ti': ['ti', 'tay', 'tai'],
    'to': ['to', 'tho', 'tu'],
    'tu': ['tu', 'thu', 'too'],
    'uh': ['uh', 'ah', 'er'],
    'up': ['up', 'ap', 'op'],
    'us': ['us', 'os', 'as'],
    'we': ['we', 'wi', 'vey'],
    'ya': ['ya', 'ia', 'dya'],
    'ye': ['ye', 'yi', 'yey'],
    'yi': ['yi', 'yay', 'ii'],
    'yo': ['yo', 'yho', 'yu'],
    'yu': ['yu', 'yhu', 'yoo'],
    'za': ['za', 'sa', 'tha'],
    'ze': ['ze', 'si', 'sey'],
    'zi': ['zi', 'say', 'sai'],
    'zo': ['zo', 'sho', 'su'],
    'zu': ['zu', 'shu', 'soo'],

    // Level 3 words
    'ace': ['ace', 'ays', 'es'],
    'act': ['act', 'akt', 'ak'],
    'add': ['add', 'ad', 'aed'],
    'age': ['age', 'eyj', 'edz'],
    'ago': ['ago', 'agho', 'agu'],
    'air': ['air', 'ayr', 'er'],
    'all': ['all', 'ol', 'al'],
    'and': ['and', 'end', 'an'],
    'any': ['any', 'eni', 'eni'],
    'ape': ['ape', 'eyp', 'ep'],
    'app': ['app', 'ap', 'ep'],
    'arc': ['arc', 'ark', 'ak'],
    'are': ['are', 'ar', 'er'],
    'ark': ['ark', 'ak', 'arc'],
    'arm': ['arm', 'am', 'arem'],
    'art': ['art', 'at', 'art'],
    'ash': ['ash', 'as', 'ash'],
    'ask': ['ask', 'ask', 'ak'],
    'ate': ['ate', 'eyt', 'et'],
    'axe': ['axe', 'aks', 'eks'],
    'bad': ['bad', 'bat', 'bade'],
    'bag': ['bag', 'beg', 'bak'],
    'ban': ['ban', 'ben', 'pan'],
    'bar': ['bar', 'ber', 'bahr'],
    'bat': ['bat', 'bet', 'bat'],
    'bay': ['bay', 'bey', 'bei'],
    'bed': ['bed', 'bid', 'bet'],
    'bee': ['bee', 'bi', 'be'],
    'beg': ['beg', 'beg', 'beyg'],
    'bet': ['bet', 'bet', 'bat'],
    'bin': ['bin', 'ben', 'pin'],
    'boa': ['boa', 'bowa', 'buwa'],
    'bob': ['bob', 'bab', 'bop'],
    'boo': ['boo', 'bu', 'bo'],
    'bop': ['bop', 'bap', 'pop'],
    'bow': ['bow', 'bao', 'bo'],
    'box': ['box', 'boks', 'baks'],
    'boy': ['boy', 'boi', 'bey'],
    'bug': ['bug', 'bag', 'bog'],
    'bun': ['bun', 'ban', 'bon'],
    'bus': ['bus', 'bas', 'bos'],
    'but': ['but', 'bat', 'bot'],
    'buy': ['buy', 'bai', 'bay'],
    'bye': ['bye', 'bai', 'bay'],
    'cab': ['cab', 'kap', 'kab'],
    'can': ['can', 'kan', 'kayn'],
    'cap': ['cap', 'kap', 'kep'],
    'car': ['car', 'kar', 'kotse'],
    'cat': ['cat', 'kat', 'kar'],
    'cog': ['cog', 'kog', 'kok'],
    'cop': ['cop', 'kap', 'kop'],
    'cow': ['cow', 'kao', 'kaw'],
    'cry': ['cry', 'krai', 'kri'],
    'cub': ['cub', 'kab', 'kob'],
    'cup': ['cup', 'kap', 'kop'],
    'cut': ['cut', 'kat', 'kot'],
    'dab': ['dab', 'dab', 'dep'],
    'dad': ['dad', 'ded', 'dadi'],
    'dam': ['dam', 'dem', 'dam'],
    'day': ['day', 'dey', 'de'],
    'den': ['den', 'din', 'dan'],
    'dew': ['dew', 'dyu', 'do'],
    'did': ['did', 'did', 'ded'],
    'dig': ['dig', 'deg', 'dik'],
    'dim': ['dim', 'dem', 'dim'],
    'dip': ['dip', 'dep', 'dip'],
    'doc': ['doc', 'dok', 'dak'],
    'dog': ['dog', 'dok', 'dug'],
    'dot': ['dot', 'dat', 'dot'],
    'dry': ['dry', 'drai', 'dray'],
    'due': ['due', 'dyu', 'do'],
    'dug': ['dug', 'dog', 'dag'],
    'duo': ['duo', 'dyo', 'du'],
    'dye': ['dye', 'day', 'dai'],
    'ear': ['ear', 'ir', 'yer'],
    'eat': ['eat', 'it', 'et'],
    'egg': ['egg', 'eg', 'ig'],
    'ego': ['ego', 'igo', 'egho'],
    'elf': ['elf', 'elf', 'elp'],
    'end': ['end', 'end', 'ind'],
    'eve': ['eve', 'iv', 'eb'],
    'fab': ['fab', 'fap', 'feb'],
    'fad': ['fad', 'fed', 'fad'],
    'fan': ['fan', 'pan', 'fen'],
    'far': ['far', 'far', 'fah'],
    'fat': ['fat', 'pat', 'fet'],
    'fax': ['fax', 'faks', 'feks'],
    'fed': ['fed', 'fid', 'fed'],
    'fee': ['fee', 'fi', 'fe'],
    'few': ['few', 'fyu', 'pyu'],
    'fig': ['fig', 'fik', 'pig'],
    'fin': ['fin', 'pin', 'fen'],
    'fit': ['fit', 'pit', 'fet'],
    'fix': ['fix', 'fiks', 'feks'],
    'fly': ['fly', 'flai', 'flay'],
    'foe': ['foe', 'fo', 'fow'],
    'fog': ['fog', 'fug', 'fok'],
    'for': ['for', 'for', 'far'],
    'fox': ['fox', 'foks', 'faks'],
    'fry': ['fry', 'frai', 'fray'],
    'fun': ['fun', 'fan', 'pan'],
    'fur': ['fur', 'fer', 'fah'],
    'gag': ['gag', 'geg', 'gak'],
    'gap': ['gap', 'gap', 'kap'],
    'gas': ['gas', 'ges', 'gas'],
    'gem': ['gem', 'jem', 'dgem'],
    'get': ['get', 'get', 'get'],
    'got': ['got', 'got', 'gat'],
    'gum': ['gum', 'gam', 'gom'],
    'gut': ['gut', 'gat', 'got'],
    'guy': ['guy', 'gay', 'gai'],
    'gym': ['gym', 'jim', 'dzhim'],
    'had': ['had', 'hed', 'had'],
    'ham': ['ham', 'hem', 'ham'],
    'has': ['has', 'hes', 'has'],
    'hat': ['hat', 'het', 'hat'],
    'hay': ['hay', 'hey', 'hei'],
    'hen': ['hen', 'hin', 'hen'],
    'her': ['her', 'her', 'her'],
    'hid': ['hid', 'hid', 'hed'],
    'him': ['him', 'him', 'hem'],
    'hip': ['hip', 'hip', 'hip'],
    'his': ['his', 'hiz', 'his'],
    'hit': ['hit', 'het', 'hit'],
    'hog': ['hog', 'hag', 'hog'],
    'hop': ['hop', 'hap', 'hop'],
    'hot': ['hot', 'hat', 'ot'],
    'how': ['how', 'hao', 'haw'],
    'hub': ['hub', 'hab', 'hab'],
    'hue': ['hue', 'hyu', 'hyu'],
    'huf': ['huf', 'haf', 'hup'],
    'hug': ['hug', 'hag', 'hog'],
    'hum': ['hum', 'ham', 'hom'],
    'hut': ['hut', 'hat', 'hot'],
    'ice': ['ice', 'ays', 'is'],
    'ill': ['ill', 'il', 'el'],
    'imp': ['imp', 'imp', 'imp'],
    'ink': ['ink', 'ink', 'enk'],
    'ion': ['ion', 'ayon', 'yon'],
    'its': ['its', 'its', 'its'],
    'jam': ['jam', 'djam', 'dsham'],
    'jar': ['jar', 'djar', 'dshar'],
    'jaw': ['jaw', 'djo', 'dsho'],
    'jet': ['jet', 'djet', 'dshet'],
    'jog': ['jog', 'djog', 'dshog'],
    'key': ['key', 'ki', 'ki'],
    'kin': ['kin', 'kin', 'ken'],
    'kit': ['kit', 'ket', 'kit'],
    'lab': ['lab', 'lab', 'lap'],
    'lag': ['lag', 'leg', 'lag'],
    'lap': ['lap', 'lep', 'lap'],
    'law': ['law', 'lao', 'lo'],
    'lay': ['lay', 'ley', 'lei'],
    'led': ['led', 'lid', 'led'],
    'leg': ['leg', 'leg', 'lig'],
    'let': ['let', 'let', 'let'],
    'lid': ['lid', 'led', 'lid'],
    'lip': ['lip', 'lep', 'lip'],
    'log': ['log', 'lag', 'log'],
    'lot': ['lot', 'lat', 'lot'],
    'low': ['low', 'lao', 'lo'],
    'mad': ['mad', 'med', 'mad'],
    'man': ['man', 'men', 'man'],
    'map': ['map', 'mep', 'map'],
    'mat': ['mat', 'met', 'mat'],
    'may': ['may', 'mei', 'me'],
    'men': ['men', 'min', 'men'],
    'met': ['met', 'met', 'mat'],
    'mob': ['mob', 'mab', 'mop'],
    'mod': ['mod', 'mad', 'mod'],
    'mud': ['mud', 'mad', 'mud'],
    'mug': ['mug', 'mag', 'mog'],
    'nag': ['nag', 'neg', 'nag'],
    'nap': ['nap', 'nep', 'nap'],
    'net': ['net', 'nit', 'net'],
    'new': ['new', 'nyu', 'neo'],
    'nip': ['nip', 'nip', 'nip'],
    'nod': ['nod', 'nad', 'nod'],
    'nor': ['nor', 'nar', 'nor'],
    'not': ['not', 'nat', 'not'],
    'now': ['now', 'nao', 'naw'],
    'nut': ['nut', 'nat', 'not'],
    'oar': ['oar', 'or', 'or'],
    'odd': ['odd', 'od', 'od'],
    'off': ['off', 'of', 'of'],
    'old': ['old', 'ol', 'old'],
    'one': ['one', 'wan', 'un'],
    'orb': ['orb', 'orb', 'orb'],
    'our': ['our', 'awr', 'ar'],
    'out': ['out', 'awt', 'ot'],
    'owl': ['owl', 'ol', 'aul'],
    'own': ['own', 'on', 'on'],
    'pad': ['pad', 'ped', 'pad'],
    'pan': ['pan', 'pen', 'pan'],
    'pap': ['pap', 'pep', 'pap'],
    'par': ['par', 'per', 'par'],
    'pat': ['pat', 'pet', 'pat'],
    'paw': ['paw', 'pao', 'po'],
    'pay': ['pay', 'pei', 'pey'],
    'pea': ['pea', 'pi', 'pe'],
    'peg': ['peg', 'pig', 'peg'],
    'pen': ['pen', 'pin', 'pen'],
    'pet': ['pet', 'pit', 'pet'],
    'pie': ['pie', 'pai', 'pay'],
    'pig': ['pig', 'peg', 'pig'],
    'pin': ['pin', 'pen', 'pin'],
    'pit': ['pit', 'pet', 'pit'],
    'ply': ['ply', 'plai', 'play'],
    'pod': ['pod', 'pad', 'pod'],
    'pop': ['pop', 'pap', 'pop'],
    'pro': ['pro', 'pro', 'pro'],
    'pry': ['pry', 'prai', 'pray'],
    'pub': ['pub', 'pab', 'pub'],
    'pup': ['pup', 'pap', 'pup'],
    'put': ['put', 'pat', 'pot'],
    'rag': ['rag', 'reg', 'rag'],
    'ram': ['ram', 'rem', 'ram'],
    'ran': ['ran', 'ren', 'ran'],
    'rap': ['rap', 'rep', 'rap'],
    'rat': ['rat', 'ret', 'rat'],
    'raw': ['raw', 'rao', 'ro'],
    'ray': ['ray', 'rey', 'rei'],
    'red': ['red', 'rat', 'ret'],
    'rib': ['rib', 'reb', 'rib'],
    'rid': ['rid', 'red', 'rid'],
    'rig': ['rig', 'reg', 'rig'],
    'rim': ['rim', 'rem', 'rim'],
    'rip': ['rip', 'rep', 'rip'],
    'rod': ['rod', 'rad', 'rod'],
    'rot': ['rot', 'rat', 'rot'],
    'row': ['row', 'rao', 'ro'],
    'rub': ['rub', 'rab', 'rub'],
    'rug': ['rug', 'rag', 'rug'],
    'run': ['run', 'ran', 'ron'],
    'sad': ['sad', 'sade', 'sat'],
    'sag': ['sag', 'seg', 'sag'],
    'sap': ['sap', 'sep', 'sap'],
    'sat': ['sat', 'set', 'sat'],
    'saw': ['saw', 'sao', 'so'],
    'say': ['say', 'sey', 'sei'],
    'see': ['see', 'si', 'se'],
    'set': ['set', 'sit', 'set'],
    'sew': ['sew', 'so', 'syo'],
    'she': ['she', 'shi', 'she'],
    'shy': ['shy', 'shay', 'shai'],
    'sip': ['sip', 'sep', 'sip'],
    'sir': ['sir', 'ser', 'sir'],
    'sit': ['sit', 'set', 'sit'],
    'six': ['six', 'siks', 'seks'],
    'sky': ['sky', 'skai', 'skay'],
    'sow': ['sow', 'sao', 'so'],
    'soy': ['soy', 'soi', 'soy'],
    'spa': ['spa', 'spa', 'spa'],
    'spy': ['spy', 'spai', 'spray'],
    'sub': ['sub', 'sab', 'sub'],
    'sum': ['sum', 'sam', 'som'],
    'sun': ['sun', 'son', 'san'],
    'tab': ['tab', 'tab', 'tep'],
    'tad': ['tad', 'ted', 'tad'],
    'tag': ['tag', 'teg', 'tag'],
    'tan': ['tan', 'ten', 'tan'],
    'tap': ['tap', 'tep', 'tap'],
    'tar': ['tar', 'ter', 'tar'],
    'tax': ['tax', 'taks', 'teks'],
    'tea': ['tea', 'ti', 'te'],
    'ten': ['ten', 'tin', 'ten'],
    'the': ['the', 'de', 'di'],
    'tie': ['tie', 'tai', 'tay'],
    'tin': ['tin', 'ten', 'tin'],
    'tip': ['tip', 'tep', 'tip'],
    'toe': ['toe', 'to', 'tu'],
    'top': ['top', 'tap', 'top'],
    'toy': ['toy', 'toi', 'toy'],
    'try': ['try', 'trai', 'tray'],
    'tub': ['tub', 'tab', 'tob'],
    'tug': ['tug', 'tag', 'tog'],
    'two': ['two', 'tu', 'to'],
    'use': ['use', 'yus', 'yus'],
    'van': ['van', 'ven', 'fan'],
    'vat': ['vat', 'vet', 'fat'],
    'vow': ['vow', 'vao', 'vaw'],
    'war': ['war', 'wor', 'gar'],
    'was': ['was', 'waz', 'was'],
    'wax': ['wax', 'waks', 'weks'],
    'way': ['way', 'wey', 'wei'],
    'web': ['web', 'web', 'web'],
    'wet': ['wet', 'wit', 'wet'],
    'who': ['who', 'hu', 'hoo'],
    'why': ['why', 'way', 'wai'],
    'wig': ['wig', 'weg', 'wig'],
    'win': ['win', 'wen', 'win'],
    'won': ['won', 'wan', 'wun'],
    'wow': ['wow', 'wao', 'waw'],
    'yam': ['yam', 'yem', 'yam'],
    'yap': ['yap', 'yep', 'yap'],
    'yes': ['yes', 'yes', 'yes'],
    'yet': ['yet', 'yet', 'yet'],
    'you': ['you', 'yu', 'yo'],
    'zip': ['zip', 'sip', 'zip'],
    'zoo': ['zoo', 'su', 'zo'],

    // Level 4 words
    'able': ['able', 'eybol', 'abel'],
    'acid': ['acid', 'asid', 'asid'],
    'afar': ['afar', 'afar', 'apahr'],
    'aged': ['aged', 'eyd', 'eyjed'],
    'ages': ['ages', 'eyjes', 'edzes'],
    'alga': ['alga', 'alga', 'alga'],
    'ally': ['ally', 'alay', 'aley'],
    'also': ['also', 'olso', 'arso'],
    'alto': ['alto', 'alto', 'alto'],
    'amid': ['amid', 'amid', 'amid'],
    'amps': ['amps', 'amps', 'amps'],
    'apex': ['apex', 'apeks', 'apeks'],
    'apps': ['apps', 'aps', 'eps'],
    'arch': ['arch', 'artch', 'ark'],
    'area': ['area', 'arya', 'erya'],
    'army': ['army', 'armi', 'armey'],
    'arts': ['arts', 'arts', 'arts'],
    'atom': ['atom', 'atom', 'atom'],
    'aunt': ['aunt', 'ant', 'ant'],
    'away': ['away', 'awey', 'awei'],
    'axle': ['axle', 'aksl', 'eksel'],
    'baby': ['baby', 'beibi', 'beby'],
    'back': ['back', 'bak', 'bek'],
    'bags': ['bags', 'bags', 'beks'],
    'ball': ['ball', 'bol', 'bal'],
    'batt': ['batt', 'bat', 'bet'],
    'bake': ['bake', 'beyk', 'bek'],
    'bald': ['bald', 'bold', 'bald'],
    'bale': ['bale', 'beyl', 'bel'],
    'band': ['band', 'bend', 'band'],
    'bank': ['bank', 'bangk', 'banc'],
    'barb': ['barb', 'barb', 'barb'],
    'barn': ['barn', 'barn', 'barn'],
    'base': ['base', 'beys', 'bes'],
    'bath': ['bath', 'bat', 'baths'],
    'bats': ['bats', 'bats', 'bets'],
    'beam': ['beam', 'bim', 'bem'],
    'bean': ['bean', 'bin', 'ben'],
    'bear': ['bear', 'ber', 'beyr'],
    'beat': ['beat', 'bit', 'bet'],
    'beck': ['beck', 'bek', 'bek'],
    'beds': ['beds', 'bedz', 'beds'],
    'been': ['been', 'bin', 'ben'],
    'beep': ['beep', 'bip', 'bep'],
    'bees': ['bees', 'biz', 'beez'],
    'bell': ['bell', 'bel', 'bel'],
    'belt': ['belt', 'belt', 'belt'],
    'bend': ['bend', 'bend', 'bend'],
    'bent': ['bent', 'bent', 'bent'],
    'best': ['best', 'best', 'best'],
    'beta': ['beta', 'beyta', 'bets'],
    'bias': ['bias', 'bayas', 'bayes'],
    'bids': ['bids', 'bidz', 'bids'],
    'bike': ['bike', 'bayk', 'bek'],
    'bill': ['bill', 'bil', 'bil'],
    'bind': ['bind', 'baynd', 'bind'],
    'bird': ['bird', 'berd', 'bird'],
    'bite': ['bite', 'bayt', 'bet'],
    'bits': ['bits', 'bits', 'bets'],
    'blog': ['blog', 'blog', 'blog'],
    'blow': ['blow', 'blo', 'blaw'],
    'blue': ['blue', 'bloo', 'blu'],
    'blur': ['blur', 'bler', 'blr'],
    'boat': ['boat', 'bot', 'bawt'],
    'body': ['body', 'badi', 'bodi'],
    'bold': ['bold', 'bold', 'bold'],
    'bond': ['bond', 'bond', 'bond'],
    'bone': ['bone', 'bon', 'bown'],
    'book': ['book', 'buk', 'bok'],
    'boot': ['boot', 'but', 'buts'],
    'bore': ['bore', 'bor', 'bor'],
    'born': ['born', 'born', 'born'],
    'boss': ['boss', 'bos', 'bos'],
    'both': ['both', 'both', 'bot'],
    'bowl': ['bowl', 'bol', 'bowl'],
    'boys': ['boys', 'boyz', 'boiz'],
    'brag': ['brag', 'breg', 'brag'],
    'brew': ['brew', 'bru', 'bryu'],
    'buck': ['buck', 'bak', 'bok'],
    'bulb': ['bulb', 'bolb', 'bulp'],
    'bulk': ['bulk', 'bolk', 'bulk'],
    'bull': ['bull', 'bul', 'bol'],
    'bump': ['bump', 'bamp', 'bomp'],
    'burn': ['burn', 'bern', 'born'],
    'bush': ['bush', 'bush', 'bush'],
    'bust': ['bust', 'bast', 'bost'],
    'busy': ['busy', 'bizy', 'bizi'],
    'cafe': ['cafe', 'kafey', 'kafi'],
    'cage': ['cage', 'keyj', 'kayj'],
    'cake': ['cake', 'keyk', 'kek'],
    'call': ['call', 'kol', 'kal'],
    'calm': ['calm', 'kam', 'kalm'],
    'came': ['came', 'keym', 'kem'],
    'camp': ['camp', 'kamp', 'kemp'],
    'cane': ['cane', 'keyn', 'ken'],
    'cape': ['cape', 'keyp', 'kep'],
    'caps': ['caps', 'kaps', 'keps'],
    'card': ['card', 'kard', 'kad'],
    'care': ['care', 'ker', 'keyr'],
    'cart': ['cart', 'kart', 'kat'],
    'case': ['case', 'keys', 'kes'],
    'cash': ['cash', 'kash', 'kesh'],
    'cast': ['cast', 'kast', 'kast'],
    'cats': ['cats', 'kats', 'kets'],
    'cave': ['cave', 'keyv', 'kev'],
    'cell': ['cell', 'sel', 'sel'],
    'cent': ['cent', 'sent', 'sent'],
    'chat': ['chat', 'chat', 'chat'],
    'chef': ['chef', 'shef', 'shef'],
    'chin': ['chin', 'chin', 'chin'],
    'chip': ['chip', 'chip', 'chip'],
    'chop': ['chop', 'chop', 'chop'],
    'city': ['city', 'siti', 'siti'],
    'clam': ['clam', 'klam', 'klem'],
    'clan': ['clan', 'klan', 'klen'],
    'clap': ['clap', 'klap', 'klep'],
    'claw': ['claw', 'klo', 'klao'],
    'clay': ['clay', 'kley', 'klei'],
    'clip': ['clip', 'klip', 'klip'],
    'clog': ['clog', 'klog', 'klag'],
    'club': ['club', 'klab', 'klub'],
    'coal': ['coal', 'kol', 'kol'],
    'coat': ['coat', 'kot', 'kote'],
    'code': ['code', 'kod', 'kood'],
    'coil': ['coil', 'koil', 'koyl'],
    'coin': ['coin', 'koin', 'koin'],
    'cold': ['cold', 'kold', 'kolt'],
    'colt': ['colt', 'kolt', 'kolt'],
    'come': ['come', 'kam', 'kam'],
    'cone': ['cone', 'kon', 'kown'],
    'cook': ['cook', 'kuk', 'kok'],
    'cool': ['cool', 'kul', 'kul'],
    'coop': ['coop', 'kup', 'kop'],
    'cope': ['cope', 'kop', 'kop'],
    'copy': ['copy', 'kopi', 'kapi'],
    'cost': ['cost', 'kost', 'kost'],
    'cozy': ['cozy', 'kozi', 'kozi'],
    'crab': ['crab', 'kreb', 'krab'],
    'cram': ['cram', 'krem', 'kram'],
    'crop': ['crop', 'krop', 'krop'],
    'cubs': ['cubs', 'kubs', 'kobs'],
    'cure': ['cure', 'kyur', 'kyur'],
    'curl': ['curl', 'kerl', 'kurl'],
    'cups': ['cups', 'kups', 'keps'],
    'curb': ['curb', 'kerb', 'kurb'],
    'cute': ['cute', 'kyut', 'kyut'],
    'cyan': ['cyan', 'sayan', 'sayan'],
    'dark': ['dark', 'dark', 'dark'],
    'darn': ['darn', 'darn', 'darn'],
    'data': ['data', 'deyta', 'deyta'],
    'date': ['date', 'deyt', 'det'],
    'dame': ['dame', 'deym', 'dem'],
    'dare': ['dare', 'der', 'deyr'],
    'dart': ['dart', 'dart', 'dart'],
    'dash': ['dash', 'dash', 'dash'],
    'dawn': ['dawn', 'don', 'dawn'],
    'days': ['days', 'deyz', 'deys'],
    'dead': ['dead', 'ded', 'ded'],
    'deal': ['deal', 'dil', 'del'],
    'dear': ['dear', 'dir', 'deyr'],
    'deck': ['deck', 'dek', 'dek'],
    'deed': ['deed', 'did', 'ded'],
    'deep': ['deep', 'dip', 'dep'],
    'deer': ['deer', 'dir', 'deyr'],
    'defy': ['defy', 'defay', 'defay'],
    'dell': ['dell', 'del', 'del'],
    'demo': ['demo', 'demo', 'demo'],
    'dent': ['dent', 'dent', 'dent'],
    'desk': ['desk', 'desk', 'desk'],
    'dial': ['dial', 'dayal', 'dayel'],
    'dice': ['dice', 'days', 'dais'],
    'diet': ['diet', 'dayet', 'dayet'],
    'dime': ['dime', 'daym', 'dem'],
    'ding': ['ding', 'ding', 'ding'],
    'dirt': ['dirt', 'dert', 'dert'],
    'dish': ['dish', 'dish', 'dish'],
    'dive': ['dive', 'dayv', 'dayv'],
    'dock': ['dock', 'dok', 'dok'],
    'done': ['done', 'dan', 'don'],
    'dont': ['dont', 'dont', 'dont'],
    'door': ['door', 'dor', 'dor'],
    'dose': ['dose', 'dos', 'dos'],
    'down': ['down', 'daon', 'dawn'],
    'drag': ['drag', 'dreg', 'drag'],
    'draw': ['draw', 'dro', 'dro'],
    'drop': ['drop', 'drop', 'drop'],
    'drum': ['drum', 'dram', 'dram'],
    'duck': ['duck', 'dak', 'dok'],
    'duel': ['duel', 'dyuel', 'dyuel'],
    'dull': ['dull', 'dol', 'dol'],
    'dust': ['dust', 'dast', 'dost'],
    'duty': ['duty', 'dyuti', 'dyuti'],
    'each': ['each', 'ich', 'ich'],
    'easy': ['easy', 'izi', 'izi'],
    'edge': ['edge', 'ej', 'ej'],
    'edit': ['edit', 'edit', 'edit'],
    'eggs': ['eggs', 'egz', 'eks'],
    'else': ['else', 'els', 'els'],
    'emit': ['emit', 'emit', 'emit'],
    'envy': ['envy', 'envi', 'envi'],
    'epic': ['epic', 'epik', 'epik'],
    'euro': ['euro', 'yuro', 'yuro'],
    'even': ['even', 'even', 'even'],
    'ever': ['ever', 'ever', 'ever'],
    'exit': ['exit', 'eksit', 'eksit'],
    'face': ['face', 'feys', 'fes'],
    'fact': ['fact', 'fakt', 'fekt'],
    'fade': ['fade', 'feyd', 'fed'],
    'fail': ['fail', 'feyl', 'fel'],
    'fair': ['fair', 'fer', 'feyr'],
    'fake': ['fake', 'feyk', 'fek'],
    'fall': ['fall', 'fol', 'fal'],
    'fame': ['fame', 'feym', 'fem'],
    'fare': ['fare', 'fer', 'feyr'],
    'farm': ['farm', 'farm', 'farm'],
    'fast': ['fast', 'past', 'hast'],
    'fate': ['fate', 'feyt', 'fet'],
    'fear': ['fear', 'fir', 'feyr'],
    'feed': ['feed', 'fid', 'fed'],
    'feel': ['feel', 'fil', 'fel'],
    'feet': ['feet', 'fit', 'fet'],
    'fell': ['fell', 'fel', 'fel'],
    'felt': ['felt', 'felt', 'felt'],
    'fern': ['fern', 'fern', 'fern'],
    'file': ['file', 'fayl', 'fal'],
    'fill': ['fill', 'fil', 'fil'],
    'film': ['film', 'film', 'film'],
    'find': ['find', 'faynd', 'faynd'],
    'fine': ['fine', 'fayn', 'fen'],
    'fire': ['fire', 'fayr', 'fayr'],
    'firm': ['firm', 'firm', 'firm'],
    'fish': ['fish', 'fish', 'fish'],
    'fist': ['fist', 'fist', 'fist'],
    'fits': ['fits', 'fits', 'fits'],
    'five': ['five', 'fayv', 'fayv'],
    'flag': ['flag', 'flag', 'flag'],
    'flat': ['flat', 'flat', 'flat'],
    'flaw': ['flaw', 'flo', 'flao'],
    'flee': ['flee', 'fli', 'fli'],
    'flew': ['flew', 'flu', 'flyu'],
    'flip': ['flip', 'flip', 'flip'],
    'flow': ['flow', 'flo', 'flo'],
    'flux': ['flux', 'flaks', 'fleks'],
    'foam': ['foam', 'fom', 'fom'],
    'fold': ['fold', 'fold', 'fold'],
    'folk': ['folk', 'fok', 'folk'],
    'food': ['food', 'fud', 'fud'],
    'fool': ['fool', 'ful', 'ful'],
    'foot': ['foot', 'fut', 'fot'],
    'ford': ['ford', 'ford', 'ford'],
    'fork': ['fork', 'fork', 'fork'],
    'form': ['form', 'form', 'form'],
    'fort': ['fort', 'fort', 'fort'],
    'four': ['four', 'for', 'for'],
    'free': ['free', 'fri', 'fri'],
    'frog': ['frog', 'prog', 'pog'],
    'from': ['from', 'fram', 'from'],
    'fuel': ['fuel', 'fyuel', 'fyuel'],
    'full': ['full', 'ful', 'ful'],
    'fume': ['fume', 'fyum', 'fyum'],
    'fund': ['fund', 'fand', 'fand'],
    'funk': ['funk', 'fank', 'fank'],
    'fury': ['fury', 'fyuri', 'fyuri'],
    'fuse': ['fuse', 'fyus', 'fyus'],
    'gain': ['gain', 'geyn', 'gen'],
    'game': ['game', 'geym', 'gem'],
    'gate': ['gate', 'geyt', 'get'],
    'gave': ['gave', 'geyv', 'gev'],
    'gear': ['gear', 'gir', 'geyr'],
    'gift': ['gift', 'gift', 'gift'],
    'girl': ['girl', 'gerl', 'gerl'],
    'give': ['give', 'giv', 'giv'],
    'glad': ['glad', 'glad', 'glad'],
    'glow': ['glow', 'glo', 'glao'],
    'glue': ['glue', 'glu', 'glyu'],
    'goal': ['goal', 'gol', 'gol'],
    'goes': ['goes', 'goz', 'guz'],
    'gold': ['gold', 'gold', 'gold'],
    'golf': ['golf', 'golf', 'golf'],
    'gone': ['gone', 'gon', 'gon'],
    'good': ['good', 'gud', 'gud'],
    'grab': ['grab', 'grab', 'grab'],
    'gram': ['gram', 'grem', 'gram'],
    'gray': ['gray', 'grey', 'grei'],
    'grid': ['grid', 'grid', 'grid'],
    'grip': ['grip', 'grip', 'grip'],
    'grow': ['grow', 'gro', 'grao'],
    'hack': ['hack', 'hak', 'hek'],
    'hail': ['hail', 'heyl', 'hel'],
    'hair': ['hair', 'her', 'heyr'],
    'half': ['half', 'haf', 'haf'],
    'hall': ['hall', 'hol', 'hal'],
    'halo': ['halo', 'heylo', 'halo'],
    'halt': ['halt', 'holt', 'holt'],
    'hand': ['hand', 'hand', 'hand'],
    'hang': ['hang', 'hang', 'hang'],
    'hard': ['hard', 'hard', 'hard'],
    'harm': ['harm', 'harm', 'harm'],
    'hate': ['hate', 'heyt', 'het'],
    'have': ['have', 'hev', 'hev'],
    'head': ['head', 'hed', 'hed'],
    'hear': ['hear', 'hir', 'heyr'],
    'heat': ['heat', 'hit', 'het'],
    'help': ['help', 'help', 'help'],
    'here': ['here', 'hir', 'heyr'],
    'hero': ['hero', 'hiro', 'hiro'],
    'hide': ['hide', 'hayd', 'hayd'],
    'high': ['high', 'hay', 'hay'],
    'hill': ['hill', 'hil', 'hil'],
    'hilt': ['hilt', 'hilt', 'hilt'],
    'hint': ['hint', 'hint', 'hint'],
    'hold': ['hold', 'hold', 'hold'],
    'hole': ['hole', 'hol', 'hol'],
    'holy': ['holy', 'holi', 'holy'],
    'home': ['home', 'hom', 'hom'],
    'hook': ['hook', 'huk', 'hok'],
    'hope': ['hope', 'hop', 'hop'],
    'horn': ['horn', 'horn', 'horn'],
    'host': ['host', 'host', 'host'],
    'hour': ['hour', 'awr', 'awer'],
    'howl': ['howl', 'haul', 'haul'],
    'huge': ['huge', 'hyuj', 'hyuj'],
    'hunt': ['hunt', 'hant', 'hant'],
    'hurt': ['hurt', 'hert', 'hert'],
    'icon': ['icon', 'aykon', 'aykon'],
    'idea': ['idea', 'aydiya', 'aydiya'],
    'inch': ['inch', 'inch', 'inch'],
    'info': ['info', 'info', 'info'],
    'into': ['into', 'intu', 'intu'],
    'ions': ['ions', 'ayans', 'ayans'],
    'iron': ['iron', 'ayern', 'ayern'],
    'item': ['item', 'aytem', 'aytem'],
    'jack': ['jack', 'djak', 'djak'],
    'jail': ['jail', 'djeyl', 'djeil'],
    'jars': ['jars', 'djarz', 'djarz'],
    'jazz': ['jazz', 'djaz', 'djas'],
    'jeep': ['jeep', 'dzip', 'dzip'],
    'jobs': ['jobs', 'djobz', 'djobz'],
    'join': ['join', 'djoin', 'djoin'],
    'joke': ['joke', 'dzhok', 'dzhok'],
    'jump': ['jump', 'dzhamp', 'dzamp'],
    'just': ['just', 'dzast', 'dzast'],
    'keen': ['keen', 'kin', 'kin'],
    'keep': ['keep', 'kip', 'kip'],
    'kept': ['kept', 'kept', 'kept'],
    'kick': ['kick', 'kik', 'kik'],
    'kids': ['kids', 'kidz', 'kidz'],
    'kind': ['kind', 'kaynd', 'kaynd'],
    'king': ['king', 'king', 'king'],
    'kiss': ['kiss', 'kis', 'kis'],
    'kite': ['kite', 'kayt', 'ket'],
    'knew': ['knew', 'nyu', 'nyu'],
    'knob': ['knob', 'nob', 'nob'],
    'knot': ['knot', 'not', 'not'],
    'know': ['know', 'no', 'no'],
    'lace': ['lace', 'leys', 'les'],
    'lack': ['lack', 'lak', 'lek'],
    'lady': ['lady', 'leydi', 'ledi'],
    'lake': ['lake', 'leyk', 'lek'],
    'land': ['land', 'lend', 'land'],
    'lane': ['lane', 'leyn', 'len'],
    'last': ['last', 'last', 'last'],
    'late': ['late', 'leyt', 'let'],
    'lava': ['lava', 'lava', 'lava'],
    'lawn': ['lawn', 'lon', 'lawn'],
    'lead': ['lead', 'lid', 'led'],
    'leaf': ['leaf', 'lif', 'lef'],
    'leap': ['leap', 'lip', 'lep'],
    'left': ['left', 'left', 'left'],
    'legs': ['legs', 'legz', 'legs'],
    'less': ['less', 'les', 'les'],
    'lets': ['lets', 'lets', 'lets'],
    'liar': ['liar', 'layar', 'layar'],
    'lick': ['lick', 'lik', 'lik'],
    'like': ['like', 'layk', 'lak'],
    'line': ['line', 'layn', 'lan'],
    'link': ['link', 'link', 'link'],
    'lion': ['lion', 'layon', 'lyon'],
    'lips': ['lips', 'lipz', 'lips'],
    'list': ['list', 'list', 'list'],
    'live': ['live', 'liv', 'liv'],
    'load': ['load', 'lod', 'lod'],
    'loaf': ['loaf', 'lof', 'lof'],
    'loan': ['loan', 'lon', 'lon'],
    'lock': ['lock', 'lok', 'lok'],
    'logo': ['logo', 'logo', 'logo'],
    'lone': ['lone', 'lon', 'lon'],
    'long': ['long', 'long', 'long'],
    'loof': ['loof', 'luf', 'luf'],
    'look': ['look', 'luk', 'lok'],
    'loom': ['loom', 'lum', 'lum'],
    'loop': ['loop', 'lup', 'lop'],
    'lose': ['lose', 'luz', 'los'],
    'loss': ['loss', 'los', 'los'],
    'lost': ['lost', 'lost', 'lost'],
    'lots': ['lots', 'lots', 'lots'],
    'loud': ['loud', 'lawd', 'laud'],
    'love': ['love', 'lab', 'lub'],
    'luck': ['luck', 'lak', 'lok'],
    'made': ['made', 'meyd', 'med'],
    'mail': ['mail', 'meyl', 'mel'],
    'main': ['main', 'meyn', 'men'],
    'make': ['make', 'meyk', 'mek'],
    'male': ['male', 'meyl', 'mel'],
    'mall': ['mall', 'mol', 'mal'],
    'many': ['many', 'meni', 'meni'],
    'maps': ['maps', 'maps', 'meps'],
    'mark': ['mark', 'mark', 'mark'],
    'mask': ['mask', 'mask', 'mask'],
    'mass': ['mass', 'mas', 'mas'],
    'maze': ['maze', 'meyz', 'meys'],
    'mean': ['mean', 'min', 'men'],
    'meat': ['meat', 'mit', 'met'],
    'meet': ['meet', 'mit', 'met'],
    'melt': ['melt', 'melt', 'melt'],
    'memo': ['memo', 'memo', 'memo'],
    'mend': ['mend', 'mend', 'mend'],
    'menu': ['menu', 'menyu', 'menyu'],
    'mesh': ['mesh', 'mesh', 'mesh'],
    'mess': ['mess', 'mes', 'mes'],
    'mild': ['mild', 'mayld', 'mayld'],
    'mile': ['mile', 'mayl', 'mel'],
    'milk': ['milk', 'milk', 'milk'],
    'mind': ['mind', 'maynd', 'maynd'],
    'mine': ['mine', 'mayn', 'men'],
    'miss': ['miss', 'mis', 'mis'],
    'mist': ['mist', 'mist', 'mist'],
    'mode': ['mode', 'mod', 'mod'],
    'mold': ['mold', 'mold', 'mold'],
    'mole': ['mole', 'mol', 'mol'],
    'monk': ['monk', 'mank', 'mank'],
    'mood': ['mood', 'mud', 'mud'],
    'moon': ['moon', 'mun', 'mun'],
    'more': ['more', 'mor', 'mor'],
    'most': ['most', 'most', 'most'],
    'move': ['move', 'muv', 'muv'],
    'much': ['much', 'mach', 'mach'],
    'must': ['must', 'mast', 'mast'],
    'name': ['name', 'nem', 'nem'],
    'nave': ['nave', 'neyv', 'nev'],
    'near': ['near', 'nir', 'neyr'],
    'neat': ['neat', 'nit', 'net'],
    'neck': ['neck', 'nek', 'nek'],
    'need': ['need', 'nid', 'ned'],
    'nest': ['nest', 'nest', 'nest'],
    'news': ['news', 'nyuz', 'nyuz'],
    'next': ['next', 'nekst', 'nekst'],
    'nice': ['nice', 'nays', 'nays'],
    'nine': ['nine', 'nayn', 'nen'],
    'none': ['none', 'non', 'non'],
    'nope': ['nope', 'nop', 'nop'],
    'norm': ['norm', 'norm', 'norm'],
    'nose': ['nose', 'noz', 'nos'],
    'note': ['note', 'not', 'not'],
    'obey': ['obey', 'obey', 'obey'],
    'odds': ['odds', 'odz', 'odz'],
    'okay': ['okay', 'okei', 'okei'],
    'once': ['once', 'wans', 'wans'],
    'only': ['only', 'onli', 'onli'],
    'open': ['open', 'open', 'open'],
    'oral': ['oral', 'oral', 'oral'],
    'oval': ['oval', 'oval', 'oval'],
    'oven': ['oven', 'oven', 'oven'],
    'over': ['over', 'over', 'over'],
    'pace': ['pace', 'peys', 'pes'],
    'pack': ['pack', 'pak', 'pek'],
    'page': ['page', 'peyj', 'pej'],
    'paid': ['paid', 'peyd', 'ped'],
    'pail': ['pail', 'peyl', 'pel'],
    'pain': ['pain', 'peyn', 'pen'],
    'palm': ['palm', 'pam', 'pam'],
    'park': ['park', 'park', 'park'],
    'part': ['part', 'part', 'part'],
    'pass': ['pass', 'pas', 'pas'],
    'past': ['past', 'past', 'past'],
    'path': ['path', 'path', 'path'],
    'pave': ['pave', 'peyv', 'pev'],
    'pawn': ['pawn', 'pon', 'pon'],
    'peak': ['peak', 'pik', 'pek'],
    'peek': ['peek', 'pik', 'pek'],
    'peel': ['peel', 'pil', 'pel'],
    'peer': ['peer', 'pir', 'peyr'],
    'pens': ['pens', 'penz', 'pens'],
    'perk': ['perk', 'perk', 'perk'],
    'pest': ['pest', 'pest', 'pest'],
    'pets': ['pets', 'pets', 'pets'],
    'pick': ['pick', 'pik', 'pik'],
    'pile': ['pile', 'payl', 'pal'],
    'pill': ['pill', 'pil', 'pil'],
    'pine': ['pine', 'payn', 'pen'],
    'ping': ['ping', 'ping', 'ping'],
    'pink': ['pink', 'pink', 'pink'],
    'pint': ['pint', 'paynt', 'pent'],
    'pipe': ['pipe', 'payp', 'pep'],
    'plan': ['plan', 'plen', 'plan'],
    'play': ['play', 'pley', 'plei'],
    'plot': ['plot', 'plot', 'plot'],
    'plow': ['plow', 'plo', 'plao'],
    'plug': ['plug', 'plag', 'plag'],
    'plus': ['plus', 'plas', 'plas'],
    'pods': ['pods', 'podz', 'pods'],
    'poem': ['poem', 'poem', 'poem'],
    'poet': ['poet', 'poet', 'poet'],
    'poll': ['poll', 'pol', 'pol'],
    'pond': ['pond', 'pond', 'pond'],
    'pool': ['pool', 'pul', 'pul'],
    'poor': ['poor', 'por', 'pur'],
    'pork': ['pork', 'pork', 'pork'],
    'port': ['port', 'port', 'port'],
    'pose': ['pose', 'poz', 'pos'],
    'post': ['post', 'post', 'post'],
    'pour': ['pour', 'por', 'por'],
    'pray': ['pray', 'prey', 'prei'],
    'prep': ['prep', 'prep', 'prep'],
    'prob': ['prob', 'prob', 'prob'],
    'prop': ['prop', 'prop', 'prop'],
    'pull': ['pull', 'pul', 'pul'],
    'pump': ['pump', 'pamp', 'pomp'],
    'pure': ['pure', 'pyur', 'pyur'],
    'push': ['push', 'push', 'push'],
    'quit': ['quit', 'kwit', 'kwit'],
    'quiz': ['quiz', 'kwiz', 'kwiz'],
    'race': ['race', 'reys', 'res'],
    'rack': ['rack', 'rak', 'rek'],
    'rage': ['rage', 'reyj', 'rej'],
    'raid': ['raid', 'reyd', 'red'],
    'rail': ['rail', 'reyl', 'rel'],
    'rain': ['rain', 'reyn', 'ren'],
    'rang': ['rang', 'rang', 'rang'],
    'rank': ['rank', 'rank', 'rank'],
    'rant': ['rant', 'rant', 'rant'],
    'rare': ['rare', 'rer', 'reyr'],
    'rate': ['rate', 'reyt', 'ret'],
    'read': ['read', 'rid', 'red'],
    'real': ['real', 'ril', 'rel'],
    'redo': ['redo', 'rido', 'rido'],
    'reed': ['reed', 'rid', 'red'],
    'reef': ['reef', 'rif', 'ref'],
    'reel': ['reel', 'ril', 'rel'],
    'rest': ['rest', 'rest', 'rest'],
    'rice': ['rice', 'rays', 'rays'],
    'rich': ['rich', 'rich', 'rich'],
    'ride': ['ride', 'rayd', 'red'],
    'rift': ['rift', 'rift', 'rift'],
    'ring': ['ring', 'ring', 'ring'],
    'ripe': ['ripe', 'rayp', 'rep'],
    'rise': ['rise', 'rayz', 'rays'],
    'risk': ['risk', 'risk', 'risk'],
    'road': ['road', 'rod', 'rod'],
    'roam': ['roam', 'rom', 'rom'],
    'rock': ['rock', 'rak', 'rok'],
    'roll': ['roll', 'rol', 'rol'],
    'roof': ['roof', 'ruf', 'ruf'],
    'room': ['room', 'rum', 'rum'],
    'root': ['root', 'rut', 'rot'],
    'rope': ['rope', 'rop', 'rop'],
    'rose': ['rose', 'roz', 'ros'],
    'rule': ['rule', 'rul', 'rul'],
    'rush': ['rush', 'rash', 'rash'],
    'rust': ['rust', 'rast', 'rast'],
    'safe': ['safe', 'seyl', 'sef'],
    'said': ['said', 'sed', 'sed'],
    'sail': ['sail', 'seyl', 'sel'],
    'sake': ['sake', 'seyk', 'sek'],
    'sale': ['sale', 'seyl', 'sel'],
    'salt': ['salt', 'solt', 'solt'],
    'same': ['same', 'seym', 'sem'],
    'sand': ['sand', 'send', 'sand'],
    'save': ['save', 'seyl', 'sev'],
    'scan': ['scan', 'skan', 'sken'],
    'scar': ['scar', 'skar', 'skar'],
    'seal': ['seal', 'sil', 'sel'],
    'seat': ['seat', 'sit', 'set'],
    'seed': ['seed', 'sid', 'sed'],
    'seem': ['seem', 'sim', 'sem'],
    'seen': ['seen', 'sin', 'sen'],
    'sell': ['sell', 'sel', 'sel'],
    'send': ['send', 'send', 'send'],
    'sent': ['sent', 'sent', 'sent'],
    'sets': ['sets', 'sets', 'sets'],
    'shed': ['shed', 'shed', 'shed'],
    'shim': ['shim', 'shim', 'shim'],
    'shin': ['shin', 'shin', 'shin'],
    'ship': ['ship', 'ship', 'ship'],
    'shoe': ['shoe', 'shu', 'shu'],
    'shop': ['shop', 'shop', 'shop'],
    'shot': ['shot', 'shot', 'shot'],
    'show': ['show', 'sho', 'shao'],
    'shut': ['shut', 'shat', 'shot'],
    'sick': ['sick', 'sik', 'sik'],
    'side': ['side', 'sayd', 'sayd'],
    'sign': ['sign', 'sayn', 'san'],
    'sing': ['sing', 'sing', 'sing'],
    'sink': ['sink', 'sink', 'sink'],
    'site': ['site', 'sayt', 'set'],
    'size': ['size', 'sayz', 'says'],
    'skin': ['skin', 'skin', 'skin'],
    'skip': ['skip', 'skip', 'skip'],
    'slot': ['slot', 'slot', 'slot'],
    'slow': ['slow', 'slo', 'slao'],
    'snap': ['snap', 'snap', 'snap'],
    'snip': ['snip', 'snip', 'snip'],
    'snow': ['snow', 'sno', 'sno'],
    'soap': ['soap', 'sop', 'sop'],
    'sofa': ['sofa', 'sofa', 'sofa'],
    'soft': ['soft', 'soft', 'soft'],
    'soil': ['soil', 'soyl', 'sol'],
    'sold': ['sold', 'sold', 'sold'],
    'solo': ['solo', 'solo', 'solo'],
    'some': ['some', 'sam', 'sam'],
    'song': ['song', 'sang', 'sang'],
    'soon': ['soon', 'sun', 'sun'],
    'sort': ['sort', 'sort', 'sort'],
    'soul': ['soul', 'sol', 'sol'],
    'soup': ['soup', 'sup', 'sup'],
    'sour': ['sour', 'sawr', 'sawr'],
    'spin': ['spin', 'spin', 'spin'],
    'spot': ['spot', 'spot', 'spot'],
    'star': ['star', 'star', 'star'],
    'stay': ['stay', 'stey', 'stei'],
    'stem': ['stem', 'stem', 'stem'],
    'step': ['step', 'step', 'step'],
    'stir': ['stir', 'stir', 'stir'],
    'stop': ['stop', 'stop', 'stop'],
    'such': ['such', 'sach', 'sach'],
    'suit': ['suit', 'sut', 'sut'],
    'sure': ['sure', 'shur', 'shur'],
    'swan': ['swan', 'swan', 'swan'],
    'swap': ['swap', 'swap', 'swap'],
    'sway': ['sway', 'swey', 'swei'],
    'swim': ['swim', 'swim', 'swim'],
    'tabs': ['tabs', 'tabz', 'tabs'],
    'tail': ['tail', 'teyl', 'tel'],
    'take': ['take', 'teyk', 'tek'],
    'tale': ['tale', 'teyl', 'tel'],
    'talk': ['talk', 'tak', 'tok'],
    'tall': ['tall', 'tol', 'tal'],
    'tame': ['tame', 'teym', 'tem'],
    'tank': ['tank', 'tangk', 'tank'],
    'tape': ['tape', 'teyp', 'tep'],
    'task': ['task', 'task', 'task'],
    'taxi': ['taxi', 'taksi', 'taksi'],
    'team': ['team', 'tim', 'tem'],
    'tear': ['tear', 'tir', 'teyr'],
    'tell': ['tell', 'tel', 'tel'],
    'temp': ['temp', 'temp', 'temp'],
    'tend': ['tend', 'tend', 'tend'],
    'tent': ['tent', 'tent', 'tent'],
    'term': ['term', 'term', 'term'],
    'test': ['test', 'test', 'test'],
    'text': ['text', 'tekst', 'tekst'],
    'than': ['than', 'dhan', 'dhan'],
    'that': ['that', 'dhat', 'dat'],
    'them': ['them', 'dhem', 'dem'],
    'then': ['then', 'dhen', 'den'],
    'they': ['they', 'dhey', 'dey'],
    'this': ['this', 'dis', 'dis'],
    'thus': ['thus', 'dhas', 'das'],
    'tide': ['tide', 'tayd', 'tayd'],
    'ties': ['ties', 'tayz', 'tays'],
    'tile': ['tile', 'tayl', 'tel'],
    'till': ['till', 'til', 'til'],
    'time': ['time', 'taym', 'tem'],
    'tiny': ['tiny', 'tayni', 'tayni'],
    'told': ['told', 'told', 'told'],
    'toll': ['toll', 'tol', 'tol'],
    'tone': ['tone', 'ton', 'ton'],
    'took': ['took', 'tuk', 'tok'],
    'tool': ['tool', 'tul', 'tul'],
    'torn': ['torn', 'torn', 'torn'],
    'tour': ['tour', 'tur', 'tur'],
    'town': ['town', 'taon', 'taon'],
    'toys': ['toys', 'toz', 'toiz'],
    'trap': ['trap', 'trap', 'trap'],
    'tree': ['tree', 'tri', 'tri'],
    'trim': ['trim', 'trim', 'trim'],
    'trip': ['trip', 'trip', 'trip'],
    'true': ['true', 'tru', 'tru'],
    'tube': ['tube', 'tyub', 'tyub'],
    'tumb': ['tumb', 'tamb', 'tomb'],
    'tune': ['tune', 'tyun', 'tyun'],
    'turf': ['turf', 'terf', 'terf'],
    'turn': ['turn', 'tern', 'tern'],
    'tusk': ['tusk', 'task', 'task'],
    'twin': ['twin', 'twin', 'twin'],
    'type': ['type', 'tayp', 'tep'],
    'undo': ['undo', 'ando', 'ando'],
    'unit': ['unit', 'yunit', 'yunit'],
    'upon': ['upon', 'apon', 'apon'],
    'urge': ['urge', 'erj', 'erj'],
    'used': ['used', 'yuzd', 'yuzd'],
    'user': ['user', 'yuzer', 'yuzer'],
    'uses': ['uses', 'yuzes', 'yuzes'],
    'vain': ['vain', 'veyn', 'ven'],
    'verb': ['verb', 'verb', 'verb'],
    'very': ['very', 'veri', 'veri'],
    'vest': ['vest', 'vest', 'vest'],
    'view': ['view', 'vyu', 'vyu'],
    'vine': ['vine', 'vayn', 'ven'],
    'vote': ['vote', 'vot', 'vot'],
    'wade': ['wade', 'weyd', 'wed'],
    'wait': ['wait', 'weyt', 'wet'],
    'wake': ['wake', 'weyk', 'wek'],
    'walk': ['walk', 'wak', 'wok'],
    'wall': ['wall', 'wol', 'wal'],
    'wand': ['wand', 'wand', 'wand'],
    'want': ['want', 'want', 'want'],
    'warm': ['warm', 'warm', 'warm'],
    'warn': ['warn', 'warn', 'warn'],
    'wash': ['wash', 'wash', 'wash'],
    'wasp': ['wasp', 'wasp', 'wasp'],
    'wave': ['wave', 'weyv', 'wev'],
    'weak': ['weak', 'wik', 'wek'],
    'wear': ['wear', 'wir', 'weyr'],
    'week': ['week', 'wik', 'wek'],
    'well': ['well', 'wel', 'wel'],
    'went': ['went', 'went', 'went'],
    'were': ['were', 'wir', 'wer'],
    'west': ['west', 'west', 'west'],
    'what': ['what', 'hwat', 'wat'],
    'when': ['when', 'hwen', 'wen'],
    'where': ['where', 'hwer', 'wer'],
    'wide': ['wide', 'wayd', 'wayd'],
    'wife': ['wife', 'wayf', 'wayf'],
    'wild': ['wild', 'wayld', 'wayld'],
    'will': ['will', 'wil', 'wil'],
    'wind': ['wind', 'wind', 'wind'],
    'wing': ['wing', 'wing', 'wing'],
    'wink': ['wink', 'wink', 'wink'],
    'wipe': ['wipe', 'wayp', 'wep'],
    'wire': ['wire', 'wayr', 'wer'],
    'wise': ['wise', 'wayz', 'ways'],
    'wish': ['wish', 'wish', 'wish'],
    'with': ['with', 'with', 'with'],
    'woke': ['woke', 'wok', 'wok'],
    'wolf': ['wolf', 'wulf', 'wulf'],
    'wood': ['wood', 'wud', 'wud'],
    'wool': ['wool', 'wul', 'wul'],
    'word': ['word', 'wurd', 'wurd'],
    'work': ['work', 'work', 'work'],
    'worm': ['worm', 'worm', 'worm'],
    'worn': ['worn', 'worn', 'worn'],
    'yard': ['yard', 'yard', 'yard'],
    'yarn': ['yarn', 'yarn', 'yarn'],
    'yawn': ['yawn', 'yawn', 'yawn'],
    'year': ['year', 'yir', 'yer'],
    'yell': ['yell', 'yel', 'yel'],
    'your': ['your', 'yur', 'yor'],
    'zero': ['zero', 'ziro', 'ziro'],
    'zone': ['zone', 'zon', 'zon'],
    'zoom': ['zoom', 'zum', 'zum'],
  };

  // Get pronunciation variations for a word
  static List<String> getPronunciationVariations(String word) {
    final normalizedWord = word.toLowerCase().trim();
    final variations = <String>[normalizedWord];

    // Check if word exists in our dictionary
    if (filipinoWordVariations.containsKey(normalizedWord)) {
      variations.addAll(filipinoWordVariations[normalizedWord]!);
    }

    // Generate variations based on vowel and consonant patterns
    final generatedVariations = _generateVariations(normalizedWord);
    variations.addAll(generatedVariations);

    // Remove duplicates and return
    return variations.toSet().toList();
  }

  // Generate variations based on Filipino pronunciation patterns
  static List<String> _generateVariations(String word) {
    final variations = <String>[];

    // Apply vowel variations
    for (final entry in filipinoVowelVariations.entries) {
      for (final variation in entry.value) {
        variations.add(word.replaceAll(entry.key, variation));
      }
    }

    // Apply consonant variations
    for (final entry in filipinoConsonantVariations.entries) {
      for (final variation in entry.value) {
        variations.add(word.replaceAll(entry.key, variation));
      }
    }

    return variations;
  }

  // Calculate similarity score between two words considering Filipino variations
  static double calculateFilipinoSimilarity(String target, String hypothesis) {
    final targetVariations = getPronunciationVariations(target);
    final normalizedHypothesis = hypothesis.toLowerCase().trim();

    double maxSimilarity = 0.0;

    for (final variation in targetVariations) {
      final similarity =
          _calculateLevenshteinSimilarity(variation, normalizedHypothesis);
      if (similarity > maxSimilarity) {
        maxSimilarity = similarity;
      }
    }

    return maxSimilarity;
  }

  // Calculate Levenshtein distance similarity
  static double _calculateLevenshteinSimilarity(String s1, String s2) {
    if (s1.isEmpty) return s2.isEmpty ? 1.0 : 0.0;
    if (s2.isEmpty) return 0.0;

    final maxLength = s1.length > s2.length ? s1.length : s2.length;
    final distance = _levenshteinDistance(s1, s2);

    return 1.0 - (distance / maxLength);
  }

  // Calculate Levenshtein distance
  static int _levenshteinDistance(String s1, String s2) {
    final matrix = List.generate(
      s1.length + 1,
      (i) => List.generate(s2.length + 1, (j) => 0),
    );

    for (int i = 0; i <= s1.length; i++) {
      matrix[i][0] = i;
    }
    for (int j = 0; j <= s2.length; j++) {
      matrix[0][j] = j;
    }

    for (int i = 1; i <= s1.length; i++) {
      for (int j = 1; j <= s2.length; j++) {
        final cost = s1[i - 1] == s2[j - 1] ? 0 : 1;
        matrix[i][j] = [
          matrix[i - 1][j] + 1, // deletion
          matrix[i][j - 1] + 1, // insertion
          matrix[i - 1][j - 1] + cost, // substitution
        ].reduce((a, b) => a < b ? a : b);
      }
    }

    return matrix[s1.length][s2.length];
  }

  // Check if pronunciation matches considering Filipino variations
  static bool matchesFilipinoPronunciation(String target, String hypothesis,
      {double threshold = 0.7}) {
    final similarity = calculateFilipinoSimilarity(target, hypothesis);
    return similarity >= threshold;
  }

  // Get phonetic breakdown for Filipino words
  static List<String> getPhoneticBreakdown(String word) {
    final normalizedWord = word.toLowerCase().trim();
    final phonemes = <String>[];

    // Simple phonetic breakdown for Filipino
    for (int i = 0; i < normalizedWord.length; i++) {
      final char = normalizedWord[i];

      // Handle consonant clusters
      if (i < normalizedWord.length - 1) {
        final cluster = normalizedWord.substring(i, i + 2);
        if (cluster == 'ng' ||
            cluster == 'ts' ||
            cluster == 'dy' ||
            cluster == 'ny') {
          phonemes.add(cluster);
          i++; // Skip next character
          continue;
        }
      }

      phonemes.add(char);
    }

    return phonemes;
  }
}
